### ISSUE TITLE
Crashing when taking any spell from creative to inventory on 1.19.1

### ISSUE THREAD

**Issue by nickademas** [ZestyBlaze/SorceryCraft#10]
Time: 2022-08-03 22:22:58
Description: Ticking player

java.lang.NoSuchFieldError: field_11735
	at net.zestyblaze.sorcerycraft.api.util.SpellHelper.learnSpells(SpellHelper.java:154)
	at net.zestyblaze.sorcerycraft.item.MultiTypeSpellItem.method_7888(MultiTypeSpellItem.java:114)
	at net.minecraft.class_1799.method_7917(class_1799.java:542)
	at net.minecraft.class_1661.method_7381(class_1661.java:255)
	at net.minecraft.class_1657.method_6007(class_1657.java:567)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1657.method_5773(class_1657.java:284)
	at net.minecraft.class_3222.method_14226(class_3222.java:487)
	at net.minecraft.class_3244.method_18784(class_3244.java:268)
	at net.minecraft.class_2535.method_10754(class_2535.java:248)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.zestyblaze.sorcerycraft.api.util.SpellHelper.learnSpells(SpellHelper.java:154)
	at net.zestyblaze.sorcerycraft.item.MultiTypeSpellItem.method_7888(MultiTypeSpellItem.java:114)
	at net.minecraft.class_1799.method_7917(class_1799.java:542)
	at net.minecraft.class_1661.method_7381(class_1661.java:255)
	at net.minecraft.class_1657.method_6007(class_1657.java:567)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1657.method_5773(class_1657.java:284)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 420
	Entity Name: BrombaIInni
	Entity's Exact location: 153.85, 65.00, 22.88
	Entity's Block location: World: (153,65,22), Section: (at 9,1,6 in 9,4,1; chunk contains blocks 144,-64,16 to 159,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:487)
	at net.minecraft.class_3244.method_18784(class_3244.java:268)
	at net.minecraft.class_2535.method_10754(class_2535.java:248)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ZestyBlaze** [comment]
Turns out they removed a certain field I need for the mod in 1.19.1, I've removed usability for 1.19.1 with SorceryCraft for now, I'll work on making a fix when I get a chance

**Comment by nickademas** [comment]
![obraz](https://user-images.githubusercontent.com/46594867/182729782-96fbaaf5-d644-4051-90cf-861d70f93c92.png)
old version is still marked as compatible with 1.19.1

**Comment by ZestyBlaze** [comment]
The old one can be ignored since everyone should be installing 1.2.0
